swahili_words = [
    {"Swahili": "na", "English": "and"},
    {"Swahili": "ni", "English": ["is", "are"]},
    {"Swahili": "kwa", "English": ["for", "by", "with"]},
    {"Swahili": "ya", "English": "of"},
    {"Swahili": "mimi", "English": "I"},
    {"Swahili": "wewe", "English": "you"},
    {"Swahili": "yeye", "English": ["he", "she"]},
    {"Swahili": "sisi", "English": "we"},
    {"Swahili": "wote", "English": "all"},
    {"Swahili": "wakati", "English": "time"},
    {"Swahili": "rafiki", "English": "friend"},
    {"Swahili": "ndugu", "English": "brother"},
    {"Swahili": "kaka", "English": "brother"},
    {"Swahili": "dada", "English": "sister"},
    {"Swahili": "mama", "English": "mother"},
    {"Swahili": "baba", "English": "father"},
    {"Swahili": "ndiyo", "English": "yes"},
    {"Swahili": "hapana", "English": "no"},
    {"Swahili": "shule", "English": "school"},
    {"Swahili": "nyumba", "English": "house"},
    {"Swahili": "mtaa", "English": "street"},
    {"Swahili": "jina", "English": "name"},
    {"Swahili": "maji", "English": "water"},
    {"Swahili": "chakula", "English": "food"},
    {"Swahili": "kitabu", "English": "book"},
    {"Swahili": "soko", "English": "market"},
    {"Swahili": "pesa", "English": "money"},
    {"Swahili": "watu", "English": "people"},
    {"Swahili": "kazi", "English": "work"},
    {"Swahili": "msaada", "English": "help"},
    {"Swahili": "habari", "English": "news"},
    {"Swahili": "asubuhi", "English": "morning"},
    {"Swahili": "mchana", "English": "afternoon"},
    {"Swahili": "jioni", "English": "evening"},
    {"Swahili": "usiku", "English": "night"},
    {"Swahili": "leo", "English": "today"},
    {"Swahili": "jana", "English": "yesterday"},
    {"Swahili": "kesho", "English": "tomorrow"},
    {"Swahili": "mwezi", "English": "month"},
    {"Swahili": "mwaka", "English": "year"},
    {"Swahili": "wiki", "English": "week"},
    {"Swahili": "siku", "English": "day"},
    {"Swahili": "barabara", "English": "road"},
    {"Swahili": "nguo", "English": "clothes"},
    {"Swahili": "kiti", "English": "chair"},
    {"Swahili": "meza", "English": "table"},
    {"Swahili": "mlango", "English": "door"},
    {"Swahili": "dirisha", "English": "window"},
    {"Swahili": "gari", "English": "car"},
    {"Swahili": "baiskeli", "English": "bicycle"},
    {"Swahili": "ndege", "English": "airplane"},
    {"Swahili": "mnyama", "English": "animal"},
    {"Swahili": "mbwa", "English": "dog"},
    {"Swahili": "paka", "English": "cat"},
    {"Swahili": "simba", "English": "lion"},
    {"Swahili": "ndovu", "English": "elephant"},
    {"Swahili": "ndizi", "English": "banana"},
    {"Swahili": "tunda", "English": "fruit"},
    {"Swahili": "mango", "English": "mango"},
    {"Swahili": "embe", "English": "mango"},
    {"Swahili": "mapera", "English": "guava"},
    {"Swahili": "nanasi", "English": "pineapple"},
    {"Swahili": "chungwa", "English": "orange"},
    {"Swahili": "limau", "English": "lemon"},
    {"Swahili": "kamusi", "English": "dictionary"},
    {"Swahili": "mwongozo", "English": "guide"},
    {"Swahili": "msaada", "English": "help"},
    {"Swahili": "nina", "English": "I have"},
    {"Swahili": "una", "English": "you have"},
    {"Swahili": "ana", "English": ["he has", "she has"]},
    {"Swahili": "tuna", "English": "we have"},
    {"Swahili": "wana", "English": "they have"},
    {"Swahili": "kuwa", "English": "be"},
    {"Swahili": "kunywa", "English": "drink"},
    {"Swahili": "kula", "English": "eat"},
    {"Swahili": "kwenda", "English": "go"},
    {"Swahili": "kuja", "English": "come"},
    {"Swahili": "kufanya", "English": "do"},
    {"Swahili": "kusema", "English": "say"},
    {"Swahili": "kujua", "English": "know"},
    {"Swahili": "kusoma", "English": "read"},
    {"Swahili": "kuandika", "English": "write"},
    {"Swahili": "kuimba", "English": "sing"},
    {"Swahili": "kusikia", "English": "hear"},
    {"Swahili": "kuona", "English": "see"},
    {"Swahili": "kuamka", "English": "wake up"},
    {"Swahili": "kulala", "English": "sleep"},
    {"Swahili": "kukimbia", "English": "run"},
    {"Swahili": "kucheka", "English": "laugh"},
    {"Swahili": "kulia", "English": "cry"},
    {"Swahili": "kutembea", "English": "walk"},
    {"Swahili": "kuendesha", "English": "drive"},
    {"Swahili": "kufikiri", "English": "think"},
    {"Swahili": "kupenda", "English": "love"},
    {"Swahili": "kuchukia", "English": "hate"},
    {"Swahili": "kusafiri", "English": "travel"},
    {"Swahili": "kufanya kazi", "English": "work"},
    {"Swahili": "kutaka", "English": "want"},
    {"Swahili": "kuhitaji", "English": "need"},
    {"Swahili": "kujaribu", "English": "try"}
]

